name: 'CI'
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: ['opened', 'synchronize']
    branches:
      - 'main'
  releases:
    types: ['published']
    branches:
      - 'main'
jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true
      - run: 'moon run ci --remote --affected'
         